### ISSUE TITLE
!start / !meet does not allow unsetting of the time

### ISSUE THREAD

**Issue by jeremy-dentel** [Googer/Professor-Pine#15]
Was in a channel this morning and saw someone use `!start 9:31` instead of `!hatch 9:31` and asked how to unset the time (so it wasn't listed as meeting @ hatch time.

Looking through the code, doesn't seem to be a way to unset the time and using `null` (as the user suggested or asked if that would work) would likely cause it to say `Meeting Time: Invalid Date` since the input is passed into `moment` directly.

**Comment by ParadoxBoxx** [comment]
Development by: https://github.com/aallshouse

**Comment by jeremy-dentel** [comment]
Closed by #31 and released in v1.1.0.
