### ISSUE TITLE
Using !here before !join messes up the !start command

### ISSUE THREAD

**Issue by JuggleWithTim** [Googer/Professor-Pine#26]
Today one player arrived to a raid without signing up with !join beforehand, upon arriving he used !here and got added to the list of players being there, but not to the list of signed up players.

Trying to move forward the start-time after that with !start resulted in this error:

`@EarthGoblins, An error occurred while running the command: TypeError: Cannot read property 'members' of undefined
You shouldn't ever receive an error like this.
Please contact EarthGoblin#4735.`

The error have been reproduced and was not a one time occurrence.

**Comment by Googer** [comment]
(per DM conversation) This was caused by using an invalid bot token for the notify bot (i.e., Poppy).  Notifications (of which setting a meeting time is part of) all work as expected once this was addressed.
