### ISSUE TITLE
No 'tier' Pokemon are not being added to DB by populate-raid-bosses

### ISSUE THREAD

**Issue by ajstewart** [Googer/Professor-Pine#29]
When running `!populate-raid-bosses` currently only Pokemon with a tier assigned are being added to the DB.

This is because here:
https://github.com/Googer/Professor-Pine/blob/f72ab5888db8a993316d459e9818fa02587d887f/commands/admin/populate-raid-bosses.js#L36-L44

It is only checking for Pokemon that have a tier assigned - there is no further `else` to catch the other ones (perfect, etc).

I added an else and purely pushed the name and this populated the database as expected. The new entries for spawns, some have nicknames and some don't so I'm not sure how you want to handle that.

**Comment by ajstewart** [comment]
Yep apologies, I see now that the intended method is to enter them using the `!rare` command. I was thrown off by seeing all the data in the `Pokemon.json`. I'll close this issue.

**Comment by jeremy-dentel** [comment]
Hey @ajstewart,

This is the intended functionality of `!populate-raid-bosses`. The table is designed to house the raid bosses (and rare spawns as special Tier 7 Pokémon) for your instance of Pine.

The `!raid-boss` and `!rare` commands are intended to add new Pokémon to this table dynamically as necessary. The `pokemon.json` file is still the source for a complete list of Pokémon data and gets combined with the game master data retrieved. The table than supplements or replaces the tier, exclusive, and shiny status found within `pokemon.json`.

Note, that `!raid-boss` is intended for adding actual raid bosses, while `!rare` is intended to add rare spawns (tier 7). `!spawn` and `!want` look for tiers, so it works with both raid bosses and rare spawns (you don't want to `!rare` a current raid boss).

`!raid` looks for exclusive and tier, but restricts it to tiers 1-5, so rare spawns cannot be reported as a raid.

I know you've closed this yourself, but I wanted to put the reasoning out there anyways. :)

**Comment by ajstewart** [comment]
Thanks for explaining it, makes complete sense when I actually realised the structure!

Keep up the great additions to Pine!

**Comment by jeremy-dentel** [comment]
Glad you're enjoying them! @ajstewart did Googer get you an invite to the Pine discord server we're building out? We are trying to bridge the gap between us making updates and explaining them to users like you, since we really only announced things via the Pittsburgh discord server.
