### ISSUE TITLE
Images not loading for Pokemon with ID less than 100

### ISSUE THREAD

**Issue by ajstewart** [Googer/Professor-Pine#30]
I discovered this by having an Alakazam raid nearby as my first test and found that a lot of Gen 1 Pokemon were not having their image loaded.

In the url call the poke.number is not zero padded so the url link won't work, as the `poke.number` is just an integer value.
https://github.com/Googer/Professor-Pine/blob/67a3e9cc0bacebadad960b42a8638d48912aa55b/app/pokemon.js#L131-L138

I tested putting some crude zero padding in my version and the images then worked as expected.

**Comment by jeremy-dentel** [comment]
This is fixed in the v1.0.4 release.
