### ISSUE TITLE
New option for original poster of raid image to not be interested by default

### ISSUE THREAD

**Issue by digumo** [Googer/Professor-Pine#9]
In our community we have a large number of people who post raid screenshots with the associated phrase of "Just posting". This means they are letting people know about the raid but cannot attend themselves. Our area is more suburban and many people may be interested in a raid if they know about it but it may only be within visual range of a few people.

Suggest adding two settings.

1) a global option within settings.json
```
"users" : {
  "original_poster_isInterested": false,
}
```
or this could be included within "features"?

2) an individual user preference stored within the database which could be controlled by a command such as **!interestedWhenPosting false**

**Comment by Googer** [comment]
Correct, this is already implemented with the !auto command.
